### ISSUE TITLE
Используйте requirements.txt

### ISSUE THREAD

**Issue by ho-apps** [fed-alex/webui_test_ng#3]
@fed-alex,  привет!
Для удобства разработки, все-таки лучшим решением, будет использование requirements.txt.
Более подробнее можно ознакомиться [тут](https://pip.pypa.io/en/latest/user_guide/#requirements-files) и [тут](https://docs.microsoft.com/ru-ru/visualstudio/python/managing-required-packages-with-requirements-txt?view=vs-2019) и [тут](https://www.jetbrains.com/help/pycharm/managing-dependencies.html)

**Comment by fed-alex** [comment]
@ho-apps , приветствую!
добавил
