### ISSUE TITLE
Добавьте .gitignore

### ISSUE THREAD

**Issue by ho-apps** [fed-alex/webui_test_ng#7]
Нежелательно хранить в репе каталоги venv, .idea, .vscode и подобные.
примеры  файла .gitignore [тут](https://www.toptal.com/developers/gitignore/api/python,jetbrains+all,visualstudiocode), можно в него еще просто добавить запись с каталогом 
`venv/*`

**Comment by fed-alex** [comment]
добавил в ветку https://github.com/fed-alex/webui_test_ng/tree/add_gitignore, так норм?

**Comment by ho-apps** [comment]
> добавил в ветку https://github.com/fed-alex/webui_test_ng/tree/add_gitignore, так норм?

Ок
