### ISSUE TITLE
Тестирование только http

### ISSUE THREAD

**Issue by ho-apps** [fed-alex/webui_test_ng#9]
Проходят ли тесты сайта без https?

**Comment by fed-alex** [comment]
должны, но я не тестил на сайте без сертификата

**Comment by ho-apps** [comment]
так как временная vm для тестов работает без https, надо бы проверить.

**Comment by ho-apps** [comment]
@fed-alex оставил комментарий в Jira , там реквизиты доступа к ng-интерфесу. Ссылка превратится в тыкву после 17:00 14 июля 2021 г

**Comment by ho-apps** [comment]
> @ho-apps, отлично, спасибо!!

решение скорее всего похоже на https://stackoverflow.com/questions/53073411/selenium-webdriverexceptionchrome-failed-to-start-crashed-as-google-chrome-is

**Comment by fed-alex** [comment]
> > @ho-apps, отлично, спасибо!!
> 
> решение скорее всего похоже на https://stackoverflow.com/questions/53073411/selenium-webdriverexceptionchrome-failed-to-start-crashed-as-google-chrome-is

Решение чего?)

**Comment by fed-alex** [comment]
@ho-apps , отписался в Jira

**Comment by ho-apps** [comment]
в классы Login и Logout необходимо добавить два аргумента 
`self.options.add_argument('--no-sandbox')
 self.options.add_argument('--disable-dev-shm-usage')`
после добавления этих двух аргументов для Chrome, тесты в контейнере агента Teamcity запустились успешно

**Comment by ho-apps** [comment]
> > > @ho-apps, отлично, спасибо!!
> > 
> > 
> > решение скорее всего похоже на https://stackoverflow.com/questions/53073411/selenium-webdriverexceptionchrome-failed-to-start-crashed-as-google-chrome-is
> 
> Решение чего?)
тесты в контейнере агента Teamcity не могут запуститься, без этих изменений

**Comment by fed-alex** [comment]
@ho-apps , готово
